group/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', views.group, name="group"),
    url(r'^rates/(?P<pk>\d+)/$', views.group_rates, name="group_rates"),
    url(r'^set-group-rates/(?P<pk>\d+)/$', views.set_group_rates, name="set_group_rates"),
    url(r'^set-member-rates/(?P<pk>\d+)/$', views.set_member_rates, name="set_member_rates"),
    url(r'^create/$', views.creategroup, name="creategroup"),
    url(r'^join/(?P<secret>[\w\d-]+)/$', views.join_group, name="joingroup"),

]

log/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
__author__ = 'Lee.Gent'

urlpatterns = [
    url(r'^$', views.log_entries_redirect, name='techlogentrylist'),
    url(r'^(?P<year>\d+)/(?P<month>\d+)$', views.log_entries, name="techlogentrylist_by_date"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/technical$', views.log_entries_technical, name="techlogentrylist_technical"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/technical/print$', views.log_entries_technical_print, name="techlogentrylist_technical_print"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml$', views.log_entries_xml, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml/v1.0$', views.log_entries_xml, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml/v0.1$', views.log_entries_xml_v01, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/json$', views.log_entries_json, name="techlogentrylist_by_date_json"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/monthsummary$', views.month_summary, name="log_month_summary"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/cap398$', views.cap398, name="cap398_by_date"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/cap398/print$', views.cap398_print, name="cap398_by_date_print"),
    url(r'^add$', views.add_flight, name='addflight'),
    url(r'^addmxevent$', views.add_mx_event, name='addmxevent'),
    url(r'^(?P<pk>\d+)/$', views.view_entry, name="logentry"),
    url(r'^delete/(?P<pk>\d+)/$', views.delete_logentry, name="delete_logentry"),
    url(r'^members/$', views.group_member_list, name="group_member_list"),
    url(r'^members/(?P<member_id>\d+)/statement/$', views.group_member_statement, name="group_member_statement"),
    url(r'^members/(?P<member_id>\d+)/statement/export/$', views.group_member_statement_export, name="group_statement_export"),
    url(r'^dump-weeks/(?P<weeks>\d+)/$', views.dump_last_x_weeks, name="dump_weeks"),
]

techlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from dashboard import views
from group import urls as group_urls
from aeroplanes import urls as aeroplanes_urls
from registration import urls as registration_urls

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^registration/', include(registration_urls)),
    url(r'^dashboard', views.dashboard),
    url(r'^groups/', include(group_urls)),
    url(r'^aeroplanes/', include(aeroplanes_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

aeroplanes/models.py
from __future__ import unicode_literals
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
from django.db import models
from django.conf import settings
from django.contrib.auth.models import Group
from django.db.models import Sum, F, Value
from django.utils import timezone


class CalendarCheck(object):
    def __init__(self, check_type, check_before):
        self.check_type = check_type
        self.check_before = check_before


class FlyingHoursCheck(object):
    def __init__(self, check_type, check_in_flying_hours, check_at_flying_hours, extension):
        self.check_type = check_type
        self.check_in_flying_hours = check_in_flying_hours
        self.check_at_total_flying_hours = check_at_flying_hours
        self.extension = extension


class CheckPair(object):
    def __init__(self, flying_hours_check, calendar_check):
        self.flying_hours_check = flying_hours_check
        self.calendar_check = calendar_check


SECS_IN_HOUR=60*60
def decimalise_timedelta(timedelta):
    seconds = timedelta.total_seconds()
    return seconds / SECS_IN_HOUR


class Aeroplane(models.Model):
    MAX_HOURS_BETWEEN_CHECKS = 50
    MAX_MONTHS_BETWEEN_CHECKS = 6

    CHECK_TYPE_50_HOURS_1 = "50HOURS1"
    CHECK_TYPE_50_HOURS_2 = "50HOURS2"
    CHECK_TYPE_150_HOURS = "150HOURS"
    CHECK_TYPE_ANNUAL = "ANNUAL"

    NEXT_CHECK_MAP = {
            CHECK_TYPE_50_HOURS_1: CHECK_TYPE_50_HOURS_2,
            CHECK_TYPE_50_HOURS_2: CHECK_TYPE_150_HOURS,
            CHECK_TYPE_150_HOURS: CHECK_TYPE_50_HOURS_1,
            CHECK_TYPE_ANNUAL: CHECK_TYPE_50_HOURS_1
    }

    CHECK_TYPE_CHOICES = (
        (CHECK_TYPE_50_HOURS_1, "50 hours (first)"),
        (CHECK_TYPE_50_HOURS_2, "50 hours (second)"),
        (CHECK_TYPE_150_HOURS, "150 hours"),
        (CHECK_TYPE_ANNUAL, "Annual"),
    )

    owning_group = models.ForeignKey(Group)

    registration = models.CharField(max_length=10)
    registered = models.DateField()

    manufacturer = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    mtow = models.IntegerField()
    built = models.IntegerField()

    engine_count = models.IntegerField()
    engine = models.CharField(max_length=100)
    propeller = models.CharField(max_length=100)

    last_annual = models.DateTimeField()

    opening_tte = models.FloatField()  # hours and hundredths of hours
    opening_time = models.FloatField()
    opening_ttp = models.FloatField()

    arc_expiry = models.DateField()
    insurance_expiry = models.DateField()
    radio_expiry = models.DateField()

    mx_extension = models.IntegerField(null=True)  # Flight hour extension

    def __str__(self):
        return "{0} ({1})".format(self.registration, self.model)

    def _generate_initial_check(self):
        c = Check()
        c.aeroplane = self
        c.time = self.last_annual
        c.type = self.CHECK_TYPE_ANNUAL
        c.ttaf = self.opening_time
        c.tte = self.opening_tte
        c.ttp = self.opening_ttp
        return c

    def get_last_check(self):
        last_check = self.check_set.order_by("time").last()
        if last_check is not None:
            return last_check
        # Oh! New 'plane?
        return self._generate_initial_check()

    def get_last_check_from(self, fromdate):
        last_check = self.check_set.filter(time__lte=fromdate).order_by("time").last()
        if last_check is not None:
            return last_check
        # Oh! New 'plane?
        return self._generate_initial_check()

    def _airborne_time_since_check(self, check):
        logged_dict = self.techlogentry_set.filter(departure_time__gt=check.time).annotate(db_block_time=(F('arrival_time') - F('departure_time'))).annotate(db_airborne_time=F('db_block_time')-Value("PT10M")).aggregate(total_logged_airborne=Sum('db_airborne_time'))
        logged = logged_dict["total_logged_airborne"]
        if logged is None:
            logged = 0
        else:
            logged = decimalise_timedelta(logged)

        return logged


    @property
    def ttaf(self):
        # Current TTAF is the TTAF at the last check [or opening number] + how many AF hours since
        last_check = self.get_last_check()
        logged = self._airborne_time_since_check(last_check)
        return last_check.ttaf + logged

    @property
    def tte(self):
        # Current TTE is the TTE at the last check [or opening number] + how many flight hours since
        last_check = self.get_last_check()
        logged = self._airborne_time_since_check(last_check)
        return last_check.tte + logged

    @property
    def ttp(self):
        # Current TTP is the TTP at the last check [or opening number] + how many flight hours since
        last_check = self.get_last_check()
        logged = self._airborne_time_since_check(last_check)
        return last_check.ttp + logged

    @property
    def flown_hours_since_check(self):
        #  Sum of tech log entries
        # TODO: remove circular dependency :-/

        # Total hours minus last check hours (if any)
        # Where total is all in logbook + opening total
        last_check = self.get_last_check()

        ttaf = self.ttaf

        flown_since_last_check = ttaf - last_check.ttaf

        return flown_since_last_check

    @property
    def next_flying_hours_check(self):
        last = self.get_last_check()
        next_flying_hours_check = self.calc_next_flying_hours_check(last.type, last.ttaf, self.flown_hours_since_check)
        return next_flying_hours_check

    @property
    def next_check_pair(self):
        last = self.get_last_check()
        check_pair = self.calc_next_check_pair(last.time, self.last_annual, last.type, last.ttaf, self.flown_hours_since_check)
        return check_pair

    def calc_next_flying_hours_check(self, last_check_type, last_check_ttaf, flown_hours):
        next_check_type = self.NEXT_CHECK_MAP[last_check_type]
        next_check_in_flying_hours = self.MAX_HOURS_BETWEEN_CHECKS - flown_hours
        next_check_at_ttaf_hours = self.MAX_HOURS_BETWEEN_CHECKS + last_check_ttaf

        if self.mx_extension:
            next_check_in_flying_hours = next_check_in_flying_hours + self.mx_extension
            next_check_at_ttaf_hours = next_check_at_ttaf_hours + self.mx_extension

        return FlyingHoursCheck(next_check_type, next_check_in_flying_hours, next_check_at_ttaf_hours, self.mx_extension)

    @classmethod
    def calc_next_calendar_check(cls, last_check_at, last_annual_check_at):
        next_annual_at = last_annual_check_at + relativedelta(years=+1)
        next_50hrs_at = last_check_at + relativedelta(months=+cls.MAX_MONTHS_BETWEEN_CHECKS)

        next_check_before, next_calendar_check_is = ((next_annual_at, Aeroplane.CHECK_TYPE_ANNUAL) if next_annual_at <= next_50hrs_at else (next_50hrs_at, Aeroplane.CHECK_TYPE_50_HOURS_1))

        return CalendarCheck(next_calendar_check_is, next_check_before)

    def calc_next_check_pair(self, last_check_at, last_annual_check_at, last_check_type, last_check_ttaf, flown_hours):
        next_flying_hours_check = self.calc_next_flying_hours_check(last_check_type, last_check_ttaf, flown_hours)
        next_calendar_check = self.calc_next_calendar_check(last_check_at, last_annual_check_at)

        return CheckPair(next_flying_hours_check, next_calendar_check)


class Check(models.Model):
    aeroplane = models.ForeignKey(Aeroplane)
    time = models.DateTimeField()
    type = models.CharField(max_length=10, choices=Aeroplane.CHECK_TYPE_CHOICES)
    ttaf = models.FloatField()
    tte = models.FloatField(default=0)
    ttp = models.FloatField(default=0)

    def __str__(self):
        return "{0} check for {1} on {2} @ {3} TTAF".format(self.type, self.aeroplane, self.time, self.ttaf)

group/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import Group
from django.db import models


""" Group have aeroplanes (already done), administrators and a number of defined generic roles and static doc uploads.
They also have a secret key which will allow membership of the group.
"""


class GroupProfile(models.Model):
    CHARGE_REGIME_TACHO_HOURS = "tacho"
    CHARGE_REGIME_BLOCK_HOURS = "block2block"
    CHARGE_REGIME_HOBBS_HOURS = "hobbs"
    CHARGE_REGIME_AIRBORNE_HOURS = "airborne"

    CHARGE_REGIME_CHOICES = (
        (CHARGE_REGIME_TACHO_HOURS, "Tacho"),
        (CHARGE_REGIME_BLOCK_HOURS, "Block-to-block"),
        (CHARGE_REGIME_HOBBS_HOURS, "Hobbs"),
        (CHARGE_REGIME_AIRBORNE_HOURS, "Airborne"),
    )

    group = models.OneToOneField(Group)
    current_fuel_rebate_price_per_litre = models.FloatField()
    current_oil_rebate_price_per_litre = models.FloatField()
    secret_key = models.UUIDField(default=uuid.uuid4)

    default_rate_includes_fuel = models.BooleanField()
    default_rate_includes_oil = models.BooleanField()
    default_charge_regime = models.CharField(max_length=20, choices=CHARGE_REGIME_CHOICES, default=CHARGE_REGIME_TACHO_HOURS)
    default_cost_per_unit = models.FloatField()

    def __unicode__(self):
        return "Profile for {0}".format(self.group.name)


class GroupMemberProfile(models.Model):
    group = models.ForeignKey(GroupProfile)
    member = models.ForeignKey(settings.AUTH_USER_MODEL)
    administrator = models.BooleanField()

    current_rate_includes_fuel = models.BooleanField()
    current_rate_includes_oil = models.BooleanField()
    current_charge_regime = models.CharField(max_length=20, choices=GroupProfile.CHARGE_REGIME_CHOICES)
    current_cost_per_unit = models.FloatField()

    def __str__(self):
        return "{} - {}".format(self.group.group.name, self.member.get_username())


class GroupContact(models.Model):
    group_profile = models.ForeignKey('GroupProfile')
    name = models.CharField(max_length=50)
    role = models.CharField(max_length=50)
    contact_info = models.CharField(max_length=100)

    def __str__(self):
        return "{} ({})".format(self.name, self.role)

group/forms.py
from django.forms import widgets, inlineformset_factory, ModelForm

from group.models import GroupProfile, GroupMemberProfile


class GroupConsumableRateForm(ModelForm):
    class Meta:
        model = GroupProfile
        fields = [
                "current_fuel_rebate_price_per_litre",
                "current_oil_rebate_price_per_litre",
                "default_cost_per_unit",
        ]
        widgets = {
            "current_fuel_rebate_price_per_litre": widgets.NumberInput(attrs={'class': 'form-control'}),
            "current_oil_rebate_price_per_litre": widgets.NumberInput(attrs={'class': 'form-control'}),
            "default_cost_per_unit": widgets.NumberInput(attrs={'class': 'form-control'})
        }


InlineMemberRateForm = inlineformset_factory(
    GroupProfile,
    GroupMemberProfile,
    fields=(
        'current_cost_per_unit',
    ),
    widgets=
    {
        "current_cost_per_unit": widgets.NumberInput(attrs={'class': 'form-control'})
    },
    extra=0,
    can_delete=False
)

group/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404

from group.forms import InlineMemberRateForm, GroupConsumableRateForm
from .models import GroupProfile, GroupMemberProfile


@login_required
def group(request, pk):
    groupprofile = get_object_or_404(GroupProfile, id=pk)
    return render(request, "group/group_detail.html", {"profile": groupprofile})


@login_required
def set_group_rates(request, pk):
    groupprofile = get_object_or_404(GroupProfile, id=pk)
    if request.method == "POST":
        gcf = GroupConsumableRateForm(request.POST, request.FILES, instance=groupprofile)
        if gcf.is_valid():
            gcf.save()

    return HttpResponseRedirect(reverse("group_rates", kwargs={'pk': pk}))


@login_required
def set_member_rates(request, pk):
    groupprofile = get_object_or_404(GroupProfile, id=pk)
    if request.method == "POST":
        mrf = InlineMemberRateForm(request.POST, request.FILES, instance=groupprofile)
        if mrf.is_valid():
            mrf.save()

    return HttpResponseRedirect(reverse("group_rates", kwargs={'pk': pk}))


@login_required
def group_rates(request, pk):
    groupprofile = get_object_or_404(GroupProfile, id=pk)

    gcf = GroupConsumableRateForm(instance=groupprofile)
    mrf_qs = GroupMemberProfile.objects.filter(group=groupprofile, member__is_active=True)
    mrf = InlineMemberRateForm(instance=groupprofile, queryset=mrf_qs)

    ctx = {
        "groupprofile": groupprofile,
        "memberrateform": mrf,
        "groupconsumablesrateform": gcf
    }

    return render(request, "group/group_rates.html", ctx)


@login_required
def join_group(request, secret):
    user = request.user
    groupprofile = get_object_or_404(GroupProfile, secret_key=secret)
    group = groupprofile.group

    member_profile_exists = GroupMemberProfile.objects.filter(group=groupprofile, member=user).exists()

    if 'confirm' in request.GET:
        # Dead easy. Add our request user to the group and quit.
        # ...if they're not in there already!
        if member_profile_exists:
            return HttpResponseBadRequest("You are already a member of this Group!")

        group.user_set.add(user)

        group_member_profile = GroupMemberProfile()
        group_member_profile.group = groupprofile
        group_member_profile.member = user
        group_member_profile.administrator = False
        group_member_profile.current_rate_includes_fuel = groupprofile.default_rate_includes_fuel
        group_member_profile.current_rate_includes_oil = groupprofile.default_rate_includes_oil
        group_member_profile.current_charge_regime = groupprofile.default_charge_regime
        group_member_profile.current_cost_per_unit = groupprofile.default_cost_per_unit

        group_member_profile.save()

        return HttpResponseRedirect(reverse('dashboard'))

    if member_profile_exists:
        template = "group/group_already_joined.html"
    else:
        template = "group/group_join.html"

    return render(request, template, {"profile": groupprofile})


def creategroup(request):
    return render(request, "group/group_create.html")

group/templates/group/group_already_joined.html
{% extends "global/root.html" %}

{% load staticfiles %}

{% block content %}
    <p>You are already a member of the '{{ profile.group.name }}' group.</p>
{% endblock %}

group/templates/group/group_create.html
{% extends "global/root.html" %}

{% load staticfiles %}

{% block content %}
    NEW GROUP FORM!
{% endblock %}

group/templates/group/group_detail.html
{% extends "global/root.html" %}

{% load staticfiles %}

{% block content %}

           <div class="page-header">
  <h2>{{ profile.group.name }}</h2>
</div>

    <div class="panel panel-default">
  <div class="panel-heading">Secret key - give this to people to allow them to join the {{ profile.group.name }} group</div>
  <div class="panel-body">

      <p><a href="{% url 'joingroup' profile.secret_key %}" title="Join {{ profile.group.name }}">{{ request.META.HTTP_HOST }}{% url 'joingroup' profile.secret_key %}</a></p>

    </div>
    </div>

    <div class="panel panel-default">
  <div class="panel-heading">Group Aeroplanes</div>
  <div class="panel-body">
    <ul class="list-group">
        {% for aeroplane in profile.group.aeroplane_set.all %}
            <li class="list-group-item"><a href="{% url 'aeroplane' aeroplane.registration %}">{{ aeroplane }}</a></li>
        {% endfor %}
        </ul>
  </div>
</div>

    <div class="panel panel-default">
  <div class="panel-heading">Group Members</div>
  <div class="panel-body">
    <ul class="list-group">
        {% for user_profile in profile.groupmemberprofile_set.all %}
            <li class="list-group-item">
                {{ user_profile.member.get_full_name }} ({{ user_profile.member.get_username }})
            {% if user_profile.administrator %}
                [techlog.aero group administrator]
            {% endif %}
            </li>
        {% endfor %}
        </ul>
  </div>
</div>
    
{% endblock %}

group/templates/group/group_join.html
{% extends "global/root.html" %}

{% load staticfiles %}

{% block content %}

    <div class="page-header">
        <h2>{{ profile.group.name }}</h2>
    </div>

    <p>Do you wish to join the group '{{ profile.group.name }}'? &nbsp;<a class="btn btn-default" href="{% url 'joingroup' profile.secret_key %}?confirm" title="Confirm Group Join">Confirm join</a></p>
{% endblock %}

group/templates/group/group_rates.html
{% extends "global/root.html" %}

{% load staticfiles %}

{% block content %}

    <h2>Rates for {{ groupprofile.group.name }}</h2>
    <h3>Fuel Rates &amp; Defaults</h3>
    <form class="form-horizontal" method="post" action="{% url 'set_group_rates' groupprofile.pk %}">
        {% csrf_token %}
        <div class="form-group">
            <label class='col-sm-3 control-label'
                   for="{{ groupconsumablesrateform.current_fuel_rebate_price_per_litre.id_for_label }}">Default Fuel
                Rebate Price (inc. VAT)</label>
            <div class="col-sm-9">
                <div class="input-group">
                    <span class="input-group-addon">&pound;</span>
                    {{ groupconsumablesrateform.current_fuel_rebate_price_per_litre }}
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class='col-sm-3 control-label'
                   for="{{ groupconsumablesrateform.current_oil_rebate_price_per_litre.id_for_label }}">Default Oil
                Rebate Price (inc. VAT)</label>
            <div class="col-sm-9">
                <div class="input-group">
                    <span class="input-group-addon">&pound;</span>
                    {{ groupconsumablesrateform.current_oil_rebate_price_per_litre }}
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class='col-sm-3 control-label'
                   for="{{ groupconsumablesrateform.default_cost_per_unit.id_for_label }}">Default Rate for New
                Members</label>
            <div class="col-sm-9">
                <div class="input-group">
                    <span class="input-group-addon">&pound;</span>
                    {{ groupconsumablesrateform.default_cost_per_unit }}
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">

                <input type="submit" class="btn btn-default" value="Set"/>
            </div>
        </div>

    </form>

    <h3>Member Hourly Rates</h3>

    <form class="form-horizontal" method="post" action="{% url 'set_member_rates' groupprofile.pk %}">

        {% csrf_token %}
        {{ memberrateform.management_form }}
        {% for form in memberrateform %}
            {{ form.id }}
            <div class="form-group">
                <label class='col-sm-3 control-label'
                       for="{{ form.current_cost_per_unit.id_for_label }}">{{ form.instance.member.get_full_name }}</label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <span class="input-group-addon">&pound;</span>
                        {{ form.current_cost_per_unit }}
                    </div>
                </div>
            </div>


        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">

                <input type="submit" class="btn btn-default" value="Save"/>

            </div>
        </div>
    </form>

{% endblock %}