log/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
__author__ = 'Lee.Gent'

urlpatterns = [
    url(r'^$', views.log_entries_redirect, name='techlogentrylist'),
    url(r'^(?P<year>\d+)/(?P<month>\d+)$', views.log_entries, name="techlogentrylist_by_date"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/technical$', views.log_entries_technical, name="techlogentrylist_technical"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/technical/print$', views.log_entries_technical_print, name="techlogentrylist_technical_print"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml$', views.log_entries_xml, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml/v1.0$', views.log_entries_xml, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml/v0.1$', views.log_entries_xml_v01, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/json$', views.log_entries_json, name="techlogentrylist_by_date_json"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/monthsummary$', views.month_summary, name="log_month_summary"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/cap398$', views.cap398, name="cap398_by_date"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/cap398/print$', views.cap398_print, name="cap398_by_date_print"),
    url(r'^add$', views.add_flight, name='addflight'),
    url(r'^addmxevent$', views.add_mx_event, name='addmxevent'),
    url(r'^(?P<pk>\d+)/$', views.view_entry, name="logentry"),
    url(r'^delete/(?P<pk>\d+)/$', views.delete_logentry, name="delete_logentry"),
    url(r'^members/$', views.group_member_list, name="group_member_list"),
    url(r'^members/(?P<member_id>\d+)/statement/$', views.group_member_statement, name="group_member_statement"),
    url(r'^members/(?P<member_id>\d+)/statement/export/$', views.group_member_statement_export, name="group_statement_export"),
    url(r'^dump-weeks/(?P<weeks>\d+)/$', views.dump_last_x_weeks, name="dump_weeks"),
]

techlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from dashboard import views
from group import urls as group_urls
from aeroplanes import urls as aeroplanes_urls
from registration import urls as registration_urls

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^registration/', include(registration_urls)),
    url(r'^dashboard', views.dashboard),
    url(r'^groups/', include(group_urls)),
    url(r'^aeroplanes/', include(aeroplanes_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

log/models.py
from __future__ import unicode_literals
from django.db import models
from django.db.models import F, Value, Sum
from django.utils import timezone
from aeroplanes.models import Aeroplane, decimalise_timedelta
from group.models import GroupProfile


class TechLogEntry(models.Model):
    class Meta:
        verbose_name_plural = 'Tech Log Entries'
    aeroplane = models.ForeignKey(Aeroplane)
    commander = models.TextField(max_length=100)
    departure_location = models.TextField(max_length=100)
    arrival_location = models.TextField(max_length=100)
    departure_time = models.DateTimeField()
    arrival_time = models.DateTimeField()
    departure_tacho = models.FloatField()
    arrival_tacho = models.FloatField()
    fuel_uplift = models.FloatField()
    oil_uplift = models.FloatField()
    defects = models.TextField(max_length=200)
    check_a_completed = models.BooleanField(verbose_name='Check \'A\' Completed')

    fuel_rebate_price_per_litre = models.FloatField(verbose_name='Current price of 100LL at EGBN, inc VAT')
    oil_rebate_price_per_litre = models.FloatField(verbose_name='Current price of oil at EGBN, inc VAT')
    rate_includes_fuel = models.BooleanField()
    rate_includes_oil = models.BooleanField()
    charge_regime = models.CharField(max_length=20, choices=GroupProfile.CHARGE_REGIME_CHOICES)
    cost_per_unit = models.FloatField()

    def __str__(self):
        return "Flight in {} by {} at {} ({} to {})".format(
            self.aeroplane,
            self.commander,
            self.departure_time,
            self.departure_location,
            self.arrival_location
        )

    # engine duration, flight duration and airborne times dynamically calculated

    @property
    def engine_duration(self):
        return self.arrival_tacho - self.departure_tacho

    @property
    def flight_duration(self):
        return self.arrival_time - self.departure_time

    @property
    def airborne_time(self):
        return self.flight_duration - timezone.timedelta(minutes=10)

    def _airborne_hours_since_check(self, check):
        logged_dict = self.aeroplane.techlogentry_set.filter(departure_time__gt=check.time).filter(departure_time__lte=self.departure_time).annotate(db_block_time=(F('arrival_time') - F('departure_time'))).annotate(db_airborne_time=F('db_block_time')-Value("PT10M")).aggregate(total_logged_airborne=Sum('db_airborne_time'))
        logged = logged_dict["total_logged_airborne"]
        return logged

    @property
    def ttaf(self):
        # Last check (or initial) time + sum of times up to and including myself
        since = self.aeroplane.get_last_check_from(self.departure_time)
        logged = self._airborne_hours_since_check(since)
        return since.ttaf + decimalise_timedelta(logged)

    @property
    def tte(self):
        # Last check (or initial) TTE + sum of airborne times up to and including myself
        since = self.aeroplane.get_last_check_from(self.departure_time)
        logged = self._airborne_hours_since_check(since)
        return since.tte + decimalise_timedelta(logged)

    @property
    def ttp(self):
        # Last check (or initial) TTE + sum of airborne times up to and including myself
        since = self.aeroplane.get_last_check_from(self.departure_time)
        logged = self._airborne_hours_since_check(since)
        return since.ttp + decimalise_timedelta(logged)

    @property
    def until_next_check(self):
        # next check ttaf - my ttaf
        since = self.aeroplane.get_last_check_from(self.departure_time)
        next_check = since.ttaf + Aeroplane.MAX_HOURS_BETWEEN_CHECKS

        if self.aeroplane.mx_extension:
            next_check += self.aeroplane.mx_extension

        return next_check - self.ttaf

    @property
    def gross_cost(self):
        rate = self.cost_per_unit

        if self.charge_regime == GroupProfile.CHARGE_REGIME_TACHO_HOURS:
            cost = self.engine_duration * rate
        else:
            cost = 0

        return cost

    @property
    def fuel_rebate(self):
        if self.rate_includes_fuel:
            return self.fuel_rebate_price_per_litre * self.fuel_uplift
        return 0

    @property
    def oil_rebate(self):
        if self.rate_includes_oil:
            return self.oil_rebate_price_per_litre * self.oil_uplift
        return 0

    @property
    def rebate(self):
        return self.fuel_rebate + self.oil_rebate

    @property
    def net_cost(self):
        return self.gross_cost - self.rebate


class ConsumablesReceipt(models.Model):
    image = models.FileField()
    log_entry = models.ForeignKey("TechLogEntry")

    def __str__(self):
        return "Receipt for flight in {} by {} at {} ({} to {})".format(
            self.log_entry.aeroplane, self.log_entry.commander, self.log_entry.departure_time,
            self.log_entry.departure_location,
            self.log_entry.arrival_location
        )

log/forms.py
from datetimewidget.widgets import DateTimeWidget
from django import forms
from django.forms import widgets, inlineformset_factory, ModelForm

from aeroplanes.models import Check, Aeroplane
from .models import TechLogEntry, ConsumablesReceipt


class MXEventForm(ModelForm):
    class Meta:
        model = Check
        fields = [
                "type",
                "time",
                "ttaf",
                "tte",
                "ttp",
        ]
        widgets = {
            "time": DateTimeWidget(attrs={'id': 'time_id'}, usel10n=True, bootstrap_version=3)
        }


class MXExtensionForm(ModelForm):
    class Meta:
        model = Aeroplane
        fields = [
            "mx_extension"
        ]


class TechLogEntryForm(ModelForm):
    commander = forms.ChoiceField(widget=widgets.Select(attrs={'class': 'form-control'}))
    current_vat_rate = forms.FloatField(initial=20, widget=widgets.HiddenInput(attrs={'class': 'form-control'}))
    fuel_rebate_rate_ex_vat = forms.FloatField(required=False, label='Current price of 100LL at EGBN, exc VAT', widget=widgets.NumberInput(attrs={'class': 'form-control'}))
    oil_rebate_rate_ex_vat = forms.FloatField(required=False, label='Current price of oil at EGBN, exc VAT', widget=widgets.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = TechLogEntry
        fields = [
            "commander",
            "departure_location",
            "arrival_location",
            "departure_time",
            "arrival_time",
            "departure_tacho",
            "arrival_tacho",
            "fuel_uplift",
            "oil_uplift",
            "defects",
            "check_a_completed",
            "current_vat_rate",
            "fuel_rebate_rate_ex_vat",
            "fuel_rebate_price_per_litre",
            "oil_rebate_rate_ex_vat",
            "oil_rebate_price_per_litre"
        ]
        widgets = {
            "fuel_rebate_price_per_litre": widgets.NumberInput(attrs={'class': 'form-control'}),
            "oil_rebate_price_per_litre": widgets.NumberInput(attrs={'class': 'form-control'}),
            "fuel_uplift": widgets.NumberInput(attrs={'class': 'form-control'}),
            "oil_uplift": widgets.NumberInput(attrs={'class': 'form-control'}),
            "departure_tacho": widgets.NumberInput(attrs={'class': 'form-control'}),
            "arrival_tacho": widgets.NumberInput(attrs={'class': 'form-control'}),
            "check_a_completed": widgets.CheckboxInput(attrs={'class': 'form-control'}),
            "departure_location": widgets.TextInput(attrs={'class': 'form-control'}),
            "arrival_location": widgets.TextInput(attrs={'class': 'form-control'}),
            "defects": widgets.TextInput(attrs={'class': 'form-control'}),
            "departure_time": DateTimeWidget(attrs={'id': 'departure_time_id'}, usel10n=True, bootstrap_version=3),
            "arrival_time": DateTimeWidget(attrs={'id': 'arrival_time_id'}, usel10n=True, bootstrap_version=3),
        }


InlineConsumablesReceiptFormSet = inlineformset_factory(
        TechLogEntry,
        ConsumablesReceipt,
        fields=('image',),
        extra=2,
        widgets={"image": widgets.ClearableFileInput(attrs={'class': 'form-control'})}
)

log/templates/log/datenav.html
<div class="page-header">
    <div class="clearfix">
        <h2 class="pull-left">Tech Log for {{ aeroplane.registration }}</h2>

        <nav class="pull-right">
            {% if printview %}
                <ul class="pagination">
                    <li>
                        <a  href="{% url printview aeroplane.registration date|date:"Y" date|date:"n"%}">⎙</a>
                    </li>
                </ul>
            {% endif %}

            <ul class="pagination">

                <li>
                    <a href="{{ last_month_link }}" aria-label="Previous Month" class="hidden-print">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li><a href="#">{{ date|date:"F" }}</a></li>

                <li>
                    <a href="{{ next_month_link }}" aria-label="Next Month" class="hidden-print">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
            <ul class="pagination">
                <li>
                    <a href="{{ last_year_link }}" aria-label="Previous Year" class="hidden-print">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li><a href="#">{{ date|date:"Y" }}</a></li>

                <li>
                    <a href="{{ next_year_link }}" aria-label="Next Year" class="hidden-print">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

log/templates/log/member_statement.html
{% extends "global/root.html" %}
{% load decimaltime %}
{% load staticfiles %}

{% block content %}

        <h3>Full Statement for Capt {{ member.get_full_name }}  <a href="{% url 'group_statement_export' aeroplane.registration member.pk %}" role="button" class="btn-default btn"><span class="glyphicon glyphicon-save-file"></span></a></h3>
                <div class="table-responsive">
                    <table class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>From</th>
                            <th>To</th>

                            <th>Block Time (hh:mm)</th>
                            <th>Tacho Time (hh.%hh)</th>

                            <th>Fuel Uplift (L)</th>
                            <th>Oil Uplift (L)</th>

                            <th>Charge Rate (&pound;/unit)</th>
                            <th>Flight Cost (&pound;)</th>
                            <th>Fuel Rebate Rate (&pound;/L)</th>
                            <th>Fuel Rebate (&pound;)</th>
                            <th>Oil Rebate Rate (&pound;/L)</th>
                            <th>Oil Rebate (&pound;)</th>

                            <th>Net Cost (&pound;)</th>

                            <th>Receipts</th>
                            <th></th>

                        </tr>
                        </thead>

                        <tbody>
                        {% for entry in entries %}
                            <tr>
                                <td>{{ entry.departure_time|date:"SHORT_DATE_FORMAT" }}</td>
                                <td>{{ entry.departure_location }}</td>
                                <td>{{ entry.arrival_location }}</td>

                                <td>{{ entry.flight_duration }}</td>
                                <td>{{ entry.engine_duration|stringformat:".02f" }}</td>

                                <td>{{ entry.fuel_uplift }}</td>
                                <td>{{ entry.oil_uplift }}</td>

                                <td>{{ entry.cost_per_unit|floatformat:2 }}</td>
                                <td>{{ entry.gross_cost|floatformat:2 }}</td>
                                <td>{{ entry.fuel_rebate_price_per_litre|floatformat:2 }}</td>
                                <td>{{ entry.fuel_rebate|floatformat:2 }}</td>
                                <td>{{ entry.oil_rebate_price_per_litre|floatformat:2 }}</td>
                                <td>{{ entry.oil_rebate|floatformat:2 }}</td>
                                <td>{{ entry.net_cost|floatformat:2 }}</td>
                                <td>
                                    {% for consumables_receipt_image in entry.consumablesreceipt_set.all %}
                                        <a href="{{ consumables_receipt_image.image.url }}">Image</a>
                                    {% endfor %}

                                </td>
                            <td class="hidden-print"><a class="btn btn-default btn-sm"
                               href="{% url 'logentry' entry.aeroplane.registration entry.id %}"><span
                                class="glyphicon glyphicon-edit"></span></a></td>

                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>{{ summary.totals.block }}</strong></td>
                            <td><strong>{{ summary.totals.tacho|stringformat:".02f" }}</strong></td>
                            <td><strong>{{ summary.totals.fuel }}</strong></td>
                            <td><strong>{{ summary.totals.oil }}</strong></td>
                            <td></td>
                            <td><strong>{{ summary.totals.gross|floatformat:2 }}</strong></td>
                            <td></td>
                            <td><strong>{{ summary.totals.fuel_rebate|floatformat:2 }}</strong></td>
                            <td></td>
                            <td><strong>{{ summary.totals.oil_rebate|floatformat:2 }}</strong></td>
                            <td><strong>{{ summary.totals.net|floatformat:2 }}</strong></td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                </div>



{% endblock %}

log/templates/log/memberlist.html
{% extends "global/root.html" %}
{% load staticfiles %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">Group Member Full Statements</div>
        <div class="panel-body">
            <ul class="list-group">
                {% for member in aeroplane.owning_group.user_set.all %}
                    <a href="{% url 'group_member_statement' aeroplane.registration member.pk %}">
                    <li class="list-group-item">{{ member.get_full_name }}</li>
                    </a>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

log/templates/log/techlogentry_add.html
{% extends "global/root.html" %}
{% load decimaltime %}
{% load staticfiles %}

{% block header %}
    {# Django doesn't correctly prepend the static url if, say, S3 storage is in operation so form.medis doesn't work. Do it manually. #}
    <link href="{% static 'css/datetimepicker.css' %}" type="text/css" media="all" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
{% endblock %}


{% block content %}
    <div class="page-header">
        <h2>Add Flight for {{ aeroplane.registration }}</h2>
    </div>

    <form enctype="multipart/form-data" method="post" action="{% url 'addflight' aeroplane.registration %}">
        <table class="table">
            <tr>
                <td colspan="2"><h3>Flight Details</h3></td>
            </tr>
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td colspan="2"><h3>Consumables Receipts</h3></td>
            </tr>
            {{ receipt_formset.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" class="btn btn-default" value="Add Flight"/></td>
            </tr>
        </table>
    </form>

    <script type="text/javascript">
    function tax_scaler_event_handler(event) {
            var rate = event.data.vat_field.val();
            var scale = 1.0 + (rate / 100.0);
            var cost = $(event.target).val();
            cost *= scale;
            event.data.dest_field.val(cost);
    }

    $('#id_fuel_rebate_rate_ex_vat').keyup({
        vat_field: $('#id_current_vat_rate'),
        dest_field: $('#id_fuel_rebate_price_per_litre')
    },
    tax_scaler_event_handler);

    $('#id_oil_rebate_rate_ex_vat').keyup({
        vat_field: $('#id_current_vat_rate'),
        dest_field: $('#id_oil_rebate_price_per_litre')
    },
    tax_scaler_event_handler);
    </script>
{% endblock %}

log/templates/log/techlogentry_add_mx_event.html
{% extends "global/root.html" %}
{% load decimaltime %}
{% load staticfiles %}

{% block header %}
    {# Django doesn't correctly prepend the static url if, say, S3 storage is in operation so form.medis doesn't work. Do it manually. #}
    <link href="{% static 'css/datetimepicker.css' %}" type="text/css" media="all" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
{% endblock %}


{% block content %}
    <div class="page-header">
        <h2>Add Maintenance Event for {{ aeroplane.registration }}</h2>
    </div>
    <p>Always use the TTAF, TTE and TTP provided by the maintenance organisation if available.</p>
    <p>If given a value, please divide the minutes by 60 - this needs to be 'decimal time' for now!</p>

    <form method="post" action="{% url 'addmxevent' aeroplane.registration %}">
    <table class="table">
            {% csrf_token %}
            {{ mx_event_form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" class="btn btn-default" value="Add Event"/></td>
            </tr>

    </table>
    </form>

<h2>Extension Granted by CAMO</h2>
    <form method="post" action="{% url 'addmxevent' aeroplane.registration %}">
    <table class="table">
            {% csrf_token %}
            {{ mx_extension_form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" class="btn btn-default" value="Update Extension"/></td>
            </tr>

    </table>
    </form>

{% endblock %}

log/templates/log/techlogentry_cap398.html
{% extends "global/root.html" %}
{% load decimaltime %}
{% load staticfiles %}

{% block content %}
    {% include 'log/datenav.html' with printview='cap398_by_date_print' %}

    <ul class="nav nav-tabs">
      <li role="presentation"><a href="{% url "techlogentrylist_by_date" aeroplane.registration date|date:"Y" date|date:"n" %}" title="Tech Log" class="hidden-print">Tech Log</a></li>
      <li role="presentation"><a href="{% url "techlogentrylist_technical" aeroplane.registration date|date:"Y" date|date:"n" %}" title="TTAF/TTE Log" class="hidden-print">Times</a></li>
      <li role="presentation"><a href="{% url "log_month_summary" aeroplane.registration date|date:"Y" date|date:"n" %}" title="Cost Summary" class="hidden-print">Summary</a></li>
      <li role="presentation" class="active"><a href="{% url "cap398_by_date" aeroplane.registration date|date:"Y" date|date:"n" %}" title="CAP 398/399 View" class="hidden-print">CAP 398/399 View</a></li>
    </ul>

    <div class="table-responsive">
        <table class="table table-hover table-condensed">
            <thead>
            <tr>
                <th>Date</th>
                <th>Flights</th>
                <th>Airborne Time</th>
                <th>TTAF</th>
                <th>TTE</th>
                <th>TTP</th>
            </tr>
            </thead>
            <tbody>
            {% for entry in stat_list %}
                <tr>
                    <td>{{ entry.day|date:"SHORT_DATE_FORMAT" }}</td>
                    <td>{{ entry.flight_count }}</td>
                    <td>{{ entry.total_airborne }}</td>
                    <td>{{ entry.ttaf|humanise_longhours }}</td>
                    <td>{{ entry.tte|humanise_longhours }}</td>
                    <td>{{ entry.ttp|humanise_longhours }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

log/templates/log/techlogentry_detail.html
{% extends "global/root.html" %}
{% load decimaltime %}
{% load staticfiles %}

{% block header %}
{# Django doesn't correctly prepend the static url if, say, S3 storage is in operation so form.medis doesn't work. Do it manually. #}
    <link href="{% static 'css/datetimepicker.css' %}" type="text/css" media="all" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
{% endblock %}


{% block content %}
    <div class="page-header">
        <h2>Edit Flight on {{ entry.departure_time|date:"SHORT_DATE_FORMAT" }} - Capt {{ entry.commander }}
            ({{ entry.departure_location }} - {{ entry.arrival_location }})</h2>
    </div>

    <form enctype="multipart/form-data" method="post" action="{% url 'logentry' aeroplane.registration entry.id %}">
        <table class="table">
            <tr>
                <td colspan="2"><h3>Flight Details</h3></td>
            </tr>
            {% csrf_token %}
            {{ form.as_table }}
            <tr>
                <td colspan="2"><h3>Consumables Receipts</h3></td>
            </tr>
            {{ receipts_form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" class="btn btn-default" value="Save Flight"/></td>
            </tr>
        </table>
    </form>


{% endblock %}

log/templates/log/techlogentry_month_summary.html
{% extends "global/root.html" %}
{% load decimaltime %}
{% load staticfiles %}

{% block content %}
    {% include 'log/datenav.html' %}

    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url "techlogentrylist_by_date" aeroplane.registration date|date:"Y" date|date:"n" %}">Tech Log</a></li>
        <li role="presentation"><a href="{% url "techlogentrylist_technical" aeroplane.registration date|date:"Y" date|date:"n" %}">Times</a></li>
        <li role="presentation" class="active"><a href="{% url "log_month_summary" aeroplane.registration date|date:"Y" date|date:"n" %}">Summary</a></li>
        <li role="presentation"><a href="{% url "cap398_by_date" aeroplane.registration date|date:"Y" date|date:"n" %}">CAP 398/399 View</a></li>
    </ul>

    {% for commander, summary in logentries.items %}
        <h3>Capt {{ commander }}</h3>
                <div class="table-responsive">
                    <table class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>From</th>
                            <th>To</th>

                            <th>Block Time (hh:mm)</th>
                            <th>Tacho Time (hh.%hh)</th>

                            <th>Fuel Uplift (L)</th>
                            <th>Oil Uplift (L)</th>

                            <th>Charge Rate (&pound;/unit)</th>
                            <th>Flight Cost (&pound;)</th>
                            <th>Fuel Rebate Rate (&pound;/L)</th>
                            <th>Fuel Rebate (&pound;)</th>
                            <th>Oil Rebate Rate (&pound;/L)</th>
                            <th>Oil Rebate (&pound;)</th>

                            <th>Total Rebate (&pound;)</th>

                            <th>Net Cost (&pound;)</th>

                            <th>Receipts</th>

                        </tr>
                        </thead>

                        <tbody>
                        {% for entry in summary.flight_list %}
                            <tr>
                                <td>{{ entry.departure_time|date:"SHORT_DATE_FORMAT" }}</td>
                                <td>{{ entry.departure_location }}</td>
                                <td>{{ entry.arrival_location }}</td>

                                <td>{{ entry.flight_duration }}</td>
                                <td>{{ entry.engine_duration|stringformat:".02f" }}</td>

                                <td>{{ entry.fuel_uplift }}</td>
                                <td>{{ entry.oil_uplift }}</td>

                                <td>{{ entry.cost_per_unit|floatformat:2 }}</td>
                                <td>{{ entry.gross_cost|floatformat:2 }}</td>
                                <td>{{ entry.fuel_rebate_price_per_litre|floatformat:2 }}</td>
                                <td>{{ entry.fuel_rebate|floatformat:2 }}</td>
                                <td>{{ entry.oil_rebate_price_per_litre|floatformat:2 }}</td>
                                <td>{{ entry.oil_rebate|floatformat:2 }}</td>

                                <td>{{ entry.rebate|floatformat:2 }}</td>

                                <td>{{ entry.net_cost|floatformat:2 }}</td>
                                <td>
                                    {% for consumables_receipt_image in entry.consumablesreceipt_set.all %}
                                        <a href="{{ consumables_receipt_image.image.url }}">Image</a>
                                    {% endfor %}

                                </td>

                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>{{ summary.totals.block }}</strong></td>
                            <td><strong>{{ summary.totals.tacho|stringformat:".02f" }}</strong></td>
                            <td><strong>{{ summary.totals.fuel }}</strong></td>
                            <td><strong>{{ summary.totals.oil }}</strong></td>
                            <td></td>
                            <td><strong>{{ summary.totals.gross|floatformat:2 }}</strong></td>
                            <td></td>
                            <td><strong>{{ summary.totals.fuel_rebate|floatformat:2 }}</strong></td>
                            <td></td>
                            <td><strong>{{ summary.totals.oil_rebate|floatformat:2 }}</strong></td>
			    <td></td>
                            <td><strong>{{ summary.totals.net|floatformat:2 }}</strong></td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                </div>


    {% endfor %}



    <h3>Consumables</h3>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
            <tr>
                <th>Airborne Hours (hh:mm)</th>
                <th>Fuel Used (L)</th>
                <th>Oil Used (L)</th>
                <th>Fuel Consumption (L/a.b. hours)</th>
                <th>Oil Consumption (L/a.b. hours)</th>
            </tr>
            </thead>
            <tbody>
            <tr>
            <td>{{ consumables_summary.airborne }}</td>
            <td>{{ consumables_summary.fuel }}</td>
            <td>{{ consumables_summary.oil }}</td>
            <td>{{ consumables_summary.fuel_litres_per_hour|floatformat:2 }}</td>
            <td>{{ consumables_summary.oil_litres_per_hour|floatformat:2 }}</td>
            </tr>
            </tbody>
        </table>
    </div>

{% endblock %}